pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = "jackie_craft_talismans"
// 如果 core-lib 子模块存在，则包含为复合构建
//if (file('lib').exists()) {
//    println "Including build from lib"
//    includeBuild('lib'){
//        dependencySubstitution {
//            substitute module('com.fanxing.fx_lib:fx-lib') using project(':')
//        }
//    }
//}

include ':lib'
project(':lib').projectDir = file('lib')